<h1 align="center">Hi ðŸ‘‹, I'm Tran Ngoc Tam</h1>

---

# Latest Blog Posts 
<!-- BLOG-POST-LIST:START -->
- [Oh boy, let&#39;s see how this goes :&rpar; â€” Added a Meme monday re-post bot to get things rolling.](https://dev.to/ben/oh-boy-lets-see-how-this-goes-added-a-meme-monday-re-post-bot-to-get-things-rolling-3ip)
- [Business Analyst Interview Questions with Answers:](https://dev.to/marrmorgan/business-analyst-interview-questions-with-answers-4ndp)
- [ðŸš€ RS Calculator v0.2.0: Safer, Smarter, and Now Supports Full Math Expressions!](https://dev.to/rasa8877/rs-calculator-v020-safer-smarter-and-now-supports-full-math-expressions-2ic1)
- [Building a Paid MCP Server](https://dev.to/eugene_lobachev/building-a-paid-mcp-service-2nh4)
- [The System You Cannot Install: Dismantling Reality from Code That Was Never Written](https://dev.to/sovellaperezp/the-system-you-cannot-install-dismantling-reality-from-code-that-was-never-written-34pm)
<!-- BLOG-POST-LIST:END -->

---

# Latest stack oveflow activity
<table>
  <tr><th>Title</th><th>Link</th></tr>
  <!-- STACKOVERFLOW:START --><tr><td>getting &quot;Fatal error: Cannot declare class phpbb\di\pass\collection_pass, because the name is already in use&quot; by instaling phpbb3 on website</td><td>https://stackoverflow.com/questions/79722722/getting-fatal-error-cannot-declare-class-phpbb-di-pass-collection-pass-becaus</td></tr><tr><td>How to handle a external service timeout with php fpm in web app</td><td>https://stackoverflow.com/questions/79722576/how-to-handle-a-external-service-timeout-with-php-fpm-in-web-app</td></tr><tr><td>Forge CLI: Logged in successfully, but all commands return Your API Token is invalid</td><td>https://stackoverflow.com/questions/79722535/forge-cli-logged-in-successfully-but-all-commands-return-your-api-token-is-inv</td></tr><tr><td>Uncaught &lpar;in promise&rpar; TypeError: NetworkError when attempting to fetch resource in Laravel 12 + Livewire V3 + Vite setup</td><td>https://stackoverflow.com/questions/79722462/uncaught-in-promise-typeerror-networkerror-when-attempting-to-fetch-resource</td></tr><tr><td>Script in Python CVE-2025-49113 Not receiving the connection</td><td>https://stackoverflow.com/questions/79722326/script-in-python-cve-2025-49113-not-receiving-the-connection</td></tr><!-- STACKOVERFLOW:END -->
</table>

---


